//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yarpuz_Pansiyon_Uygulama.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlinanUrunler
    {
        public int Id { get; set; }
        public Nullable<int> Icecek { get; set; }
        public Nullable<int> Gida { get; set; }
        public Nullable<int> Cerezler { get; set; }
    }
}
