//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yarpuz_Pansiyon_Uygulama.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YarpuzPansiyonEntities2 : DbContext
    {
        public YarpuzPansiyonEntities2()
            : base("name=YarpuzPansiyonEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminGiris> AdminGiris { get; set; }
        public virtual DbSet<AlinanUrunler> AlinanUrunler { get; set; }
        public virtual DbSet<Faturalar> Faturalar { get; set; }
        public virtual DbSet<Mesajlar> Mesajlar { get; set; }
        public virtual DbSet<MusteriEkle> MusteriEkle { get; set; }
        public virtual DbSet<Oda101> Oda101 { get; set; }
        public virtual DbSet<Oda102> Oda102 { get; set; }
        public virtual DbSet<Oda103> Oda103 { get; set; }
        public virtual DbSet<Oda104> Oda104 { get; set; }
        public virtual DbSet<Oda105> Oda105 { get; set; }
        public virtual DbSet<Oda106> Oda106 { get; set; }
        public virtual DbSet<Oda107> Oda107 { get; set; }
        public virtual DbSet<Oda108> Oda108 { get; set; }
        public virtual DbSet<Oda109> Oda109 { get; set; }
    }
}
