//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yarpuz_Pansiyon_Uygulama.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriEkle
    {
        public int MusteriId { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string Cinsiyet { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string TC { get; set; }
        public string OdaNo { get; set; }
        public Nullable<int> Ucret { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
    }
}
